// 형식: ["키", "제목", "설명", "링크URL", "확장자", "고해상도원본유무"],
// 확장자: grid/thumb에 사용. video/webp/jpg.
// 고해상도: true면 lightbox에서 -lg.확장자 사용 (3840px 원본)
var imageDataList = [
  ["hero-bg", "Hero Background", "", "", "webm"],
  ["profile", "About Me", "3D Graphics & Technical Designer", "", "png"],
  ["1", "AI Robot Simulation", "IsaacSIM Learning", "", "mp4"],
  ["2", "Robot Learning & Control", "Robot Unitree A1", "", "mp4"],
  ["3", "Hydrogen Station Digital Twin", "Hydrogen Refueling Station Project", "", "jpg"],
  ["4", "Motion Graphics & Visualization", "Motion Graphics Project", "", "jpg"],
  ["5", "Terrain & Environment Simulation", "Terrain Simulation Project", "", "webm"],
  ["6", "Facility Digital Twin Platform", "Facility Digital Twin Project", "", "jpg"],
  ["7", "Infrastructure Digital Twin", "Public Works Project", "", "jpg"],
  ["8", "Brand Identity Design", "Branding Design", "", "png"],
  ["9", "Professional Certification", "Autodesk Certification", "", "png"],
];

// __AUTO_GENERATED_GALLERY_EXTRA_START__
var imageGalleryExtra = [
  ["1. AI-1","AI 로봇 시뮬레이션","Isaac Sim & AI Robotics","","jpg",false],
  ["1. AI-2","Omniverse detail 2","","","jpg",false],
  ["1. AI-3","Omniverse detail 3","","","jpg",false],
  ["1. AI-4","Omniverse detail 4","","","jpg",false],
  ["1. AI-5","Omniverse detail 5","","","jpg",false],
  ["1. AI-6","Omniverse detail 6","","","jpg",false],
  ["1. AI-7","Omniverse detail 7","","","jpg",false],
  ["1. AI-8","Omniverse detail 8","","","jpg",false],
  ["1. AI-9","Omniverse detail 9","","","jpg",false],
  ["2. Equipment-1","설비 모델링","Facility Modeling","","jpg",false],
  ["2. Equipment-2","Industrial Complex detail 2","","","jpg",false],
  ["2. Equipment-3","Industrial Complex detail 3","","","jpg",false],
  ["2. Equipment-4","Industrial Complex detail 4","","","jpg",false],
  ["2. Equipment-5","Industrial Complex detail 5","","","jpg",false],
  ["2. Equipment-6","Industrial Complex detail 6","","","jpg",false],
  ["2. Equipment-7","Industrial Complex detail 7","","","jpg",false],
  ["2. Equipment-8","Industrial Complex detail 8","","","jpg",false],
  ["2. Equipment-9","Industrial Complex detail 9","","","jpg",false],
  ["2. Equipment-10","Industrial Complex detail 10","","","jpg",false],
  ["2. Equipment-11","Industrial Complex detail 11","","","jpg",false],
  ["2. Equipment-12","Industrial Complex detail 12","","","jpg",false],
  ["2. Equipment-13","Industrial Complex detail 13","","","jpg",false],
  ["2. Equipment-14","Industrial Complex detail 14","","","jpg",false],
  ["2. Equipment-15","Industrial Complex detail 15","","","jpg",false],
  ["2. Equipment-16","Industrial Complex detail 16","","","jpg",false],
  ["2. Equipment-17","Industrial Complex detail 17","","","jpg",false],
  ["2. Equipment-18","Industrial Complex detail 18","","","jpg",false],
  ["2. Equipment-19","Industrial Complex detail 19","","","jpg",false],
  ["2. Equipment-20","Industrial Complex detail 20","","","jpg",false],
  ["2. Equipment-21","Industrial Complex detail 21","","","jpg",false],
  ["2. Equipment-22","Industrial Complex detail 22","","","jpg",false],
  ["2. Equipment-23","Industrial Complex detail 23","","","jpg",false],
  ["2. Equipment-24","Industrial Complex detail 24","","","jpg",false],
  ["2. Equipment-25","Industrial Complex detail 25","","","jpg",false],
  ["2. Equipment-26","Industrial Complex detail 26","","","jpg",false],
  ["2. Equipment-27","Industrial Complex detail 27","","","jpg",false],
  ["2. Equipment-28","Industrial Complex detail 28","","","jpg",false],
  ["3. Architecture-1","건축 시각화","Architectural Visualization","","jpg",false],
  ["3. Architecture-2","Hydrogen Refueling Station detail 2","","","jpg",false],
  ["3. Architecture-3","Hydrogen Refueling Station detail 3","","","jpg",false],
  ["3. Architecture-4","Hydrogen Refueling Station detail 4","","","jpg",false],
  ["3. Architecture-5","Hydrogen Refueling Station detail 5","","","jpg",false],
  ["3. Architecture-6","Hydrogen Refueling Station detail 6","","","jpg",false],
  ["3. Architecture-7","Hydrogen Refueling Station detail 7","","","jpg",false],
  ["3. Architecture-8","Hydrogen Refueling Station detail 8","","","jpg",false],
  ["3. Architecture-9","Hydrogen Refueling Station detail 9","","","jpg",false],
  ["3. Architecture-10","Hydrogen Refueling Station detail 10","","","jpg",false],
  ["3. Architecture-11","Hydrogen Refueling Station detail 11","","","jpg",false],
  ["3. Architecture-12","Hydrogen Refueling Station detail 12","","","jpg",false],
  ["3. Architecture-13","Hydrogen Refueling Station detail 13","","","jpg",false],
  ["3. Architecture-14","Hydrogen Refueling Station detail 14","","","jpg",false],
  ["4. Geographic-1","GIS 공간정보 모델링","GIS & Geospatial Modeling","","jpg",false],
  ["4. Geographic-2","Motion Graphics detail 2","","","jpg",false],
  ["4. Geographic-3","Motion Graphics detail 3","","","jpg",false],
  ["4. Geographic-4","Motion Graphics detail 4","","","jpg",false],
  ["4. Geographic-5","Motion Graphics detail 5","","","jpg",false],
  ["4. Geographic-6","Motion Graphics detail 6","","","jpg",false],
  ["4. Geographic-7","Motion Graphics detail 7","","","jpg",false],
  ["4. Geographic-8","Motion Graphics detail 8","","","jpg",false],
  ["4. Geographic-9","Motion Graphics detail 9","","","jpg",false],
  ["4. Geographic-10","Motion Graphics detail 10","","","jpg",false],
  ["4. Geographic-11","Motion Graphics detail 11","","","jpg",false],
  ["4. Geographic-12","Motion Graphics detail 12","","","jpg",false],
  ["4. Geographic-13","Motion Graphics detail 13","","","jpg",false],
  ["4. Geographic-14","Motion Graphics detail 14","","","jpg",false],
  ["5. System-1","시스템 개발 및 디지털 트윈","System Development & Digital Twin","","jpg",false],
  ["5. System-2","Terrain Simulation detail 2","","","jpg",false],
  ["5. System-3","Terrain Simulation detail 3","","","jpg",false],
  ["5. System-4","Terrain Simulation detail 4","","","jpg",false],
  ["5. System-5","Terrain Simulation detail 5","","","jpg",false],
  ["5. System-6","Terrain Simulation detail 6","","","jpg",false],
  ["5. System-7","Terrain Simulation detail 7","","","jpg",false],
  ["5. System-8","Terrain Simulation detail 8","","","jpg",false],
  ["6. Video editing-1","영상 편집 및 모션그래픽","Video Editing & Motion Graphics","","jpg",false],
  ["6. Video editing-2","Facility Digital Twin detail 2","","","jpg",false],
  ["6. Video editing-3","Facility Digital Twin detail 3","","","jpg",false],
  ["6. Video editing-4","Facility Digital Twin detail 4","","","jpg",false],
  ["6. Video editing-5","Facility Digital Twin detail 5","","","jpg",false],
  ["6. Video editing-6","Facility Digital Twin detail 6","","","jpg",false],
  ["6. Video editing-7","Facility Digital Twin detail 7","","","jpg",false],
  ["6. Video editing-8","Facility Digital Twin detail 8","","","jpg",false],
];

// __AUTO_GENERATED_GALLERY_EXTRA_END__
