// 형식: ["키", "제목", "설명", "링크URL", "확장자", "고해상도원본유무"],
// 확장자: grid/thumb에 사용. video/webp/jpg.
// 고해상도: true면 lightbox에서 -lg.확장자 사용 (3840px 원본)
var imageDataList = [
  ["hero-bg", "Hero Background", "", "", "webm"],
  ["profile", "About Me", "3D Graphics & Technical Designer", "", "jpg"],
  ["1", "Omniverse", "IsaacSIM Learning test", "", "mp4"],
  ["2", "Industrial Park", "Industrial Project", "", "jpg"],
  ["3", "Project 3", "test3", "", "jpg"],
  ["4", "Project 4", "Description", "", "jpg"],
  ["5", "Project 5", "Description", "", "webm"],
  ["6", "Project 6", "Description", "", "jpg"],
  ["7", "Project 7", "Description", "", "jpg"],
  ["8", "Project 8", "Description", "", "jpg"],
  ["9", "Project 9", "Description", "", "jpg"],
];

// __AUTO_GENERATED_GALLERY_EXTRA_START__
var imageGalleryExtra = [
  ["1-1","Omniverse detail 1","","","jpg",false],
  ["1-2","Omniverse detail 2","","","jpg",false],
  ["1-3","Omniverse detail 3","","","jpg",false],
  ["1-4","Omniverse detail 4","","","jpg",false],
  ["1-5","Omniverse detail 5","","","jpg",false],
  ["2-1","Industrial Park detail 1","","","jpg",false],
  ["2-2","Industrial Park detail 2","","","jpg",false],
  ["2-3","Industrial Park detail 3","","","jpg",false],
  ["2-4","Industrial Park detail 4","","","jpg",false],
  ["2-5","Industrial Park detail 5","","","jpg",false],
  ["2-6","Industrial Park detail 6","","","jpg",false],
  ["2-7","Industrial Park detail 7","","","jpg",false],
  ["2-8","Industrial Park detail 8","","","jpg",false],
  ["2-9","Industrial Park detail 9","","","jpg",false],
  ["3-1","Project 3 detail 1","","","jpg",false],
  ["3-2","Project 3 detail 2","","","jpg",false],
  ["3-3","Project 3 detail 3","","","jpg",false],
  ["3-4","Project 3 detail 4","","","jpg",false],
  ["3-5","Project 3 detail 5","","","jpg",false],
  ["3-6","Project 3 detail 6","","","jpg",false],
  ["3-7","Project 3 detail 7","","","jpg",false],
  ["3-8","Project 3 detail 8","","","jpg",false],
  ["3-9","Project 3 detail 9","","","jpg",false],
  ["3-10","Project 3 detail 10","","","jpg",false],
  ["3-11","Project 3 detail 11","","","jpg",false],
  ["3-12","Project 3 detail 12","","","jpg",false],
  ["3-13","Project 3 detail 13","","","jpg",false],
  ["3-14","Project 3 detail 14","","","jpg",false],
  ["4-1","Project 4 detail 1","","","jpg",false],
  ["4-2","Project 4 detail 2","","","jpg",false],
  ["4-3","Project 4 detail 3","","","jpg",false],
  ["4-4","Project 4 detail 4","","","jpg",false],
  ["4-5","Project 4 detail 5","","","jpg",false],
  ["4-6","Project 4 detail 6","","","jpg",false],
  ["4-7","Project 4 detail 7","","","jpg",false],
  ["4-8","Project 4 detail 8","","","jpg",false],
  ["4-9","Project 4 detail 9","","","jpg",false],
  ["5-1","Project 5 detail 1","","","png",false],
  ["6-1","Project 6 detail 1","","","jpg",false],
  ["6-2","Project 6 detail 2","","","jpg",false],
  ["7-1","Project 7 detail 1","","","jpg",false],
  ["7-2","Project 7 detail 2","","","jpg",false],
  ["7-3","Project 7 detail 3","","","jpg",false],
  ["8-1","Project 8 detail 1","","","jpg",false],
  ["8-2","Project 8 detail 2","","","jpg",false],
  ["8-3","Project 8 detail 3","","","jpg",false],
  ["9-1","Project 9 detail 1","","","jpg",false],
  ["9-2","Project 9 detail 2","","","jpg",false],
  ["9-3","Project 9 detail 3","","","jpg",false],
];

// __AUTO_GENERATED_GALLERY_EXTRA_END__
