// 형식: ["키", "제목", "설명", "링크URL", "확장자", "고해상도원본유무"],
// 확장자: grid/thumb에 사용. video/webp/jpg.
// 고해상도: true면 lightbox에서 -lg.확장자 사용 (3840px 원본)
var imageDataList = [
  ["hero-bg", "Hero Background", "", "", "webm"],
  ["profile", "About Me", "3D Graphics & Technical Designer", "", "png"],
  ["1", "AI 로봇 시뮬레이션", "자율주행 및 강화학습 검증 환경", "", "mp4"],
  ["2", "지능형 로봇 제어", "로봇 제어 및 학습 플랫폼", "", "mp4"],
  ["3", "스마트시티 디지털트윈", "GIS 기반 도시 운영 플랫폼", "", "jpg"],
  ["4", "산업설비 디지털트윈", "생산설비 시각화 및 운영관리", "", "jpg"],
  ["5", "3D GIS 플랫폼", "공간정보 기반 디지털트윈 구축", "", "webm"],
  ["6", "플랜트 디지털트윈", "실시간 설비 관제 시스템", "", "jpg"],
  ["7", "도시관제 디지털트윈", "통합 도시 운영 및 분석 플랫폼", "", "jpg"],
  ["8", "브랜드 아이덴티티 디자인", "브랜딩 및 공간 디자인 솔루션", "", "png"],
  ["9", "전문 교육 인증", "Autodesk 공인 교육 프로그램", "", "png"],
];

// __AUTO_GENERATED_GALLERY_EXTRA_START__
var imageGalleryExtra = [
  ["1-1","AI 로봇 시뮬레이션","Isaac Sim & AI Robotics","","jpg",false],
  ["1-2","Omniverse detail 2","","","jpg",false],
  ["1-3","Omniverse detail 3","","","jpg",false],
  ["1-4","Omniverse detail 4","","","jpg",false],
  ["1-5","Omniverse detail 5","","","jpg",false],
  ["1-6","Omniverse detail 6","","","jpg",false],
  ["1-7","Omniverse detail 7","","","jpg",false],
  ["1-8","Omniverse detail 8","","","jpg",false],
  ["1-9","Omniverse detail 9","","","jpg",false],
  ["2-1","설비 모델링","Facility Modeling","","jpg",false],
  ["2-2","Industrial Complex detail 2","","","jpg",false],
  ["2-3","Industrial Complex detail 3","","","jpg",false],
  ["2-4","Industrial Complex detail 4","","","jpg",false],
  ["2-5","Industrial Complex detail 5","","","jpg",false],
  ["2-6","Industrial Complex detail 6","","","jpg",false],
  ["2-7","Industrial Complex detail 7","","","jpg",false],
  ["2-8","Industrial Complex detail 8","","","jpg",false],
  ["2-9","Industrial Complex detail 9","","","jpg",false],
  ["2-10","Industrial Complex detail 10","","","jpg",false],
  ["2-11","Industrial Complex detail 11","","","jpg",false],
  ["2-12","Industrial Complex detail 12","","","jpg",false],
  ["2-13","Industrial Complex detail 13","","","jpg",false],
  ["2-14","Industrial Complex detail 14","","","jpg",false],
  ["2-15","Industrial Complex detail 15","","","jpg",false],
  ["2-16","Industrial Complex detail 16","","","jpg",false],
  ["2-17","Industrial Complex detail 17","","","jpg",false],
  ["2-18","Industrial Complex detail 18","","","jpg",false],
  ["2-19","Industrial Complex detail 19","","","jpg",false],
  ["2-20","Industrial Complex detail 20","","","jpg",false],
  ["2-21","Industrial Complex detail 21","","","jpg",false],
  ["2-22","Industrial Complex detail 22","","","jpg",false],
  ["2-23","Industrial Complex detail 23","","","jpg",false],
  ["2-24","Industrial Complex detail 24","","","jpg",false],
  ["2-25","Industrial Complex detail 25","","","jpg",false],
  ["3-1","건축 시각화","Architectural Visualization","","jpg",false],
  ["3-2","Hydrogen Refueling Station detail 2","","","jpg",false],
  ["3-3","Hydrogen Refueling Station detail 3","","","jpg",false],
  ["3-4","Hydrogen Refueling Station detail 4","","","jpg",false],
  ["3-5","Hydrogen Refueling Station detail 5","","","jpg",false],
  ["3-6","Hydrogen Refueling Station detail 6","","","jpg",false],
  ["3-7","Hydrogen Refueling Station detail 7","","","jpg",false],
  ["3-8","Hydrogen Refueling Station detail 8","","","jpg",false],
  ["3-9","Hydrogen Refueling Station detail 9","","","jpg",false],
  ["3-10","Hydrogen Refueling Station detail 10","","","jpg",false],
  ["3-11","Hydrogen Refueling Station detail 11","","","jpg",false],
  ["3-12","Hydrogen Refueling Station detail 12","","","jpg",false],
  ["3-13","Hydrogen Refueling Station detail 13","","","jpg",false],
  ["3-14","Hydrogen Refueling Station detail 14","","","jpg",false],
  ["4-1","GIS 공간정보 모델링","GIS & Geospatial Modeling","","jpg",false],
  ["4-2","Motion Graphics detail 2","","","jpg",false],
  ["4-3","Motion Graphics detail 3","","","jpg",false],
  ["4-4","Motion Graphics detail 4","","","jpg",false],
  ["4-5","Motion Graphics detail 5","","","jpg",false],
  ["4-6","Motion Graphics detail 6","","","jpg",false],
  ["4-7","Motion Graphics detail 7","","","jpg",false],
  ["4-8","Motion Graphics detail 8","","","jpg",false],
  ["4-9","Motion Graphics detail 9","","","jpg",false],
  ["4-10","Motion Graphics detail 10","","","jpg",false],
  ["4-11","Motion Graphics detail 11","","","jpg",false],
  ["4-12","Motion Graphics detail 12","","","jpg",false],
  ["4-13","Motion Graphics detail 13","","","jpg",false],
  ["4-14","Motion Graphics detail 14","","","jpg",false],
  ["5-1","시스템 개발 및 디지털 트윈","System Development & Digital Twin","","jpg",false],
  ["5-2","Terrain Simulation detail 2","","","jpg",false],
  ["5-3","Terrain Simulation detail 3","","","jpg",false],
  ["5-4","Terrain Simulation detail 4","","","jpg",false],
  ["5-5","Terrain Simulation detail 5","","","jpg",false],
  ["5-6","Terrain Simulation detail 6","","","jpg",false],
  ["5-7","Terrain Simulation detail 7","","","jpg",false],
  ["5-8","Terrain Simulation detail 8","","","jpg",false],
  ["5-9","Terrain Simulation detail 9","","","jpg",false],
  ["6-1","영상 편집 및 모션그래픽","Video Editing & Motion Graphics","","jpg",false],
  ["6-2","Facility Digital Twin detail 2","","","jpg",false],
  ["6-3","Facility Digital Twin detail 3","","","jpg",false],
  ["6-4","Facility Digital Twin detail 4","","","jpg",false],
  ["6-5","Facility Digital Twin detail 5","","","jpg",false],
  ["6-6","Facility Digital Twin detail 6","","","jpg",false],
  ["6-7","Facility Digital Twin detail 7","","","jpg",false],
  ["6-8","Facility Digital Twin detail 8","","","jpg",false],
];

// __AUTO_GENERATED_GALLERY_EXTRA_END__
